export { default as Home } from "./Home";
export { default as Features } from "./Features";
export { default as Contact } from "./Contact";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as FAQ } from "./support/FAQ";
export { default as Documentation } from "./support/Documentation";
export { default as AdminDashboard } from "./dashboard/AdminDashboard";
export { default as TeacherDashboard } from "./dashboard/TeacherDashboard";
export { default as EnrollmentOfficerDashboard } from "./dashboard/EnrollmentOfficerDashboard";
export { default as AccountantDashboard } from "./dashboard/AccountantDashboard.tsx";
export { default as HeadTeacherDashboard } from "./dashboard/HeadTeacherDashboard";
export { default as AddStudent } from "./dashboard/AddStudent";
export { default as ViewStudent } from "./dashboard/ViewStudent";
export { default as ViewTeacher } from "./dashboard/ViewTeacher";
export { default as AddUser } from "./dashboard/AddUser.tsx";
export { default as AddClass } from "./dashboard/AddClass";
export { default as ViewClass } from "./dashboard/ViewClass";
export { default as AddSubject } from "./dashboard/AddSubject";
export { default as ViewSubject } from "./dashboard/ViewSubject.tsx"
export { default as AddAttendance } from "./dashboard/AddAttendance.tsx"
export { default as AddExam } from "./dashboard/AddExam.tsx"
export { default as AddStudentMarks } from "./dashboard/AddStudentsMarks.tsx"
export { default as ViewExam } from "./dashboard/ViewExam.tsx"
export { default as ViewStudentTotalMarks } from "./dashboard/ViewStudentTotalMarks.tsx"
export { default as ViewAttendance } from "./dashboard/ViewAttendance.tsx"
